### ISSUE TITLE
Move to the JupyterLab GitHub organization

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/extension-examples#22]
This meta-issue tracks the points that should be addressed before moving the repo to the JupyterLab GitHub organization.

The process to add a new repo is described here: https://github.com/jupyterlab/team-compass/pull/12

- [x] Follow the same style convention: #4 
- [x] Update all the examples: #14 
- [x] Setup tooling to embed code snippets into the README files: #20 
- [x] Add server extension example: #19 
- [x] Move to ESLint: #49 
- [x] Change license to the standard Jupyter license and copyright: #75
- [x] Do a final pass on the wording and writing style
- [x] Open a new issue on https://github.com/jupyterlab/team-compass

**Comment by jtpio** [comment]
We should probably wait for the 2.0 release and [migrate to it](https://github.com/jtpio/jupyterlab-extension-examples/issues/68) before making an official announcement / proposal.

**Comment by jtpio** [comment]
Thanks @echarles and @fcollonval for all the work.

Almost all items have been checked. We could do a final pass to spot typos and other small things (`let` / `const`). 

And then open the issue on https://github.com/jupyterlab/team-compass to start the migration process, with links to all relevant (documentation) issues that people have been posting.

Is there anything missing that we should do before?

**Comment by fcollonval** [comment]
Thanks to you too @jtpio 😃 

> other small things (`let` / `const`)

The linter enforces the use of `const` for unmodified variable (#72) 😉

**Comment by echarles** [comment]
We are good today to open the issue on team-compass. Thx @jtpio for pushing this repo forward.

**Comment by jtpio** [comment]
Perfect, I'll open the issue tomorrow then.

> The linter enforces the use of `const` for unmodified variable (#72) wink

That is even better :sunglasses:

**Comment by jtpio** [comment]
Issue on the team compass: https://github.com/jupyterlab/team-compass/issues/44

**Comment by blink1073** [comment]
Nicely done!
